1. Create a python program to find duplicate files by content. User will 
input path and it will scan all directories, sub-directories to find all 
duplicates files.
Delete the found duplicate file

In [ ]:
import hashlib
import os

path="C://Users/shragrawal/Desktop"
dirList=os.walk(path)

hashList=[]
dupList=[]
for (dir_path,dir_names,file_names) in os.walk(path):
    print(dir_path,dir_names,file_names)
    for i in file_names:
        file_path=os.path.join(dir_path,i)
        if '.txt' in i:
            fileObj=open(file_path,'r')
            str1=fileObj.read().encode()
            hash1=hashlib.sha256(str1)
        
            if hash1.hexdigest() in hashList:
                dupList.append(i)
                os.remove(file_path)      # deleting the duplicate file
            else:
                hashList.append(hash1.hexdigest())
        
     

            
print("dupList = ",dupList)  

2. Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.

In [7]:
import string
import random

result_string = ''.join(random.choice(string.ascii_uppercase))
result_string+=''.join(random.choice(string.ascii_lowercase) for x in range(2))
result_string+=''.join(random.choice(string.digits)for x in range(2))
result_string+=''.join(random.choice(string.punctuation))

str_final=list(result_string)
random.shuffle(str_final)
password=''.join(str_final)
print(password)

3n/3Fh


     3. Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number

In [10]:
import numpy as np
def prime(n):
    count=0
    if(n<2):
        return False
    for i in range(2,n//2+1):
       
        if n%i==0:
            count+=1
    if (count==0):
        return True
    else:
        return False
    



        

In [22]:
row=int(input(" enter number of rows"))
column=int(input(" enter number of columns"))

arr4=np.ones((row,column))
for i in range(row):
    for j in range(column):
        arr4[i][j]=int(input(" enter your values"))
        
x=0
for i in range(row):
    for j in range(column):
        
        if (prime(x)):
            arr4[i][j]=arr4[i][j]**3
            x+=1
        else:
            x+=1
print(arr4)            

 enter number of rows3
 enter number of columns3
 enter your values1
 enter your values2
 enter your values3
 enter your values4
 enter your values5
 enter your values6
 enter your values7
 enter your values8
 enter your values9
[[  1.   2.  27.]
 [ 64.   5. 216.]
 [  7. 512.   9.]]


    4. Python program to get the sum of every cubed value and its previous integer. 

In [23]:
x=0
prev_val=0
for i in range(row):
    for j in range(column):
      
        if (prime(x)):
            arr4[i][j]=arr4[i][j]+prev_val
            prev_val=arr4[i][j]
            x+=1
        else:
            prev_val=arr4[i][j]
            x+=1
print(arr4)            

[[  1.   2.  29.]
 [ 93.   5. 221.]
 [  7. 519.   9.]]


    5. Given two arrays, find their intersection. Examples:
     Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6 ]

In [15]:
import numpy as np

arr1=np.array([1, 3, 4, 5, 7])
arr2=np.array([2, 3, 5, 6])
intersection_array=[]
for i in arr1:
    for j in arr2:
        if i==j:
            intersection_array.append(j)
                        

In [16]:
print(intersection_array)

[3, 5]


    6. Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same

In [21]:
arr3=np.ones((7,7))

x=1
for i in range(len(arr3)):
    for j in range(len(arr3[i])):
        arr3[i][j]= arr3[i][j]*x*7
        x+=1
        
print(arr3[6][6])        


343.0


    7. Checker Board Patten using Numpy:
     [   1   0   1   0   1   0   1
         0   1   0   1   0   1   0
         1   0   1   0   1   0   1
         0   1   0   1   0   1   0
         1   0   1   0   1   0   1  ]

In [9]:
arr4=np.ones((5,7),dtype="int8")
arr4[1::2,0::2]=0
arr4[0::2,1::2]=0
print(arr4)

[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


    8. Create a given Matrix:
    [  A,     B,     C,       D
       E,      F,     G,       H
       I,      a,      K,       L
       M,    N,     o,       P
       Q,     R,      S,       T
       U,     0,     W,      O ]
     Replace all the vowels by np.nan
     A, E, I, O U  -- >  np.nan
     Return the count of the missing values

In [8]:
import numpy as np
import string

list1=list(string.ascii_uppercase[:-2])
vowel =['A','E','I','O','U']
count=0

for i in range(0,len(list1)):
    if list1[i] in vowel:
        list1[i]=np.nan
        count+=1
        
array_1=np.array(list1).reshape(6,4)
print(array_1)
print("Number of missing values : ",count)


[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'J' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' 'V' 'W' 'X']]
Number of missing values :  5
